###Topics: Adding, Drop,Trucate,iter,sort_values,adding row

#Adding New Column to existing columns

###Add a New Column to an Existing Datframe using DataFrame.insert()

In [ ]:
import pandas as pd

# Define a dictionary containing Students data
data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

In [ ]:
df

     Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc

###Adding Columns to Pandas DataFrame using Dataframe.assign()
This method will create a new dataframe with a new column added to the old dataframe.

In [ ]:
import pandas as pd

# Define a dictionary containing Students data
data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}


# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# Using 'Address' as the column name and equating it to the list
df2 = df.assign(address=['Delhi', 'Bangalore', 'Chennai', 'Patna'])

print(df2)

     Name  Height Qualification    address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna

###Pandas Add Column to DataFrame using a Dictionary

In [ ]:
# Import pandas package
import pandas as pd

# Define a dictionary containing Students data
data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}

In [ ]:
# Define a dictionary with key values of
# an existing column and their respective
# value pairs as the # values for our new column.
address = {'Jai': 'Delhi', 'Princi': 'Bangalore',
           'Gaurav': 'Patna', 'Anuj': 'Chennai'}

In [ ]:
# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
df

     Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc

In [ ]:
# Provide 'Address' as the column name
df['Address'] = df['Name'].map(address)

# Observe the output
print(df)

     Name  Height Qualification Address
0     Jai     5.1           Msc     NaN
1  Princi     6.2            MA     NaN
2  Gaurav     5.1           Msc     NaN
3    Anuj     5.2           Msc     NaN

###Adding a New Column to a Pandas DataFrame using List

In [ ]:
# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
df

     Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc

In [ ]:
# Declare a list that is to be converted into a column
address = ['Delhi', 'Bangalore', 'Chennai', 'Patna']

# Using 'Address' as the column name
# and equating it to the list
df['Address'] = address

print(df)

     Name  Height Qualification    Address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna

###Add A New Column To An Existing Pandas DataFrame using Dataframe.loc()

In [ ]:
import pandas as pd

data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
       'Height': [5.1, 6.2, 5.1, 5.2],
       'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}
df=pd.DataFrame(data)

In [ ]:
df

     Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc

In [ ]:
# Create the list of new column values
address = ["Delhi", "Bangalore", "Chennai", "Patna"]

# Add the new column using loc
df.loc[:,"Address"] = address

print(df)

     Name  Height Qualification    Address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna

###Adding More than One columns in Existing Dataframe

In [ ]:
import pandas as pd

data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Address': ['Delhi', 'Bangalore', 'Chennai', 'Patna']}

df = pd.DataFrame(data)
df

     Name  Height Qualification    Address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna

In [ ]:
# Define new data for additional columns
age = [22, 25, 23, 24]
state = ['NCT', 'Karnataka', 'Tamil Nadu', 'Bihar']

In [ ]:
# Add multiple columns using dictionary assignment
new_data = {'Age': age,'State': state }
df = df.assign(**new_data)

print(df)

     Name  Height Qualification    Address  Age       State
0     Jai     5.1           Msc      Delhi   22         NCT
1  Princi     6.2            MA  Bangalore   25   Karnataka
2  Gaurav     5.1           Msc    Chennai   23  Tamil Nadu
3    Anuj     5.2           Msc      Patna   24       Bihar

#Python | Delete rows/columns from DataFrame using Pandas.drop()

**Syntax: DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors=’raise’)**

**Parameters:**

labels: String or list of strings referring row or column name.

axis: int or string value, 0 ‘index’ for Rows and 1 ‘columns’ for Columns.

index or columns: Single label or list. index or columns are an alternative to axis and cannot be used together.
level: Used to specify level in case data frame is having multiple level index.

inplace: Makes changes in original Data Frame if True.

errors: Ignores error if any value from the list doesn’t exists and drops rest of the values when errors = ‘ignore’

**Return type: Dataframe with dropped values**

In [ ]:
# importing pandas module
import pandas as pd

# making data frame from csv file
data = pd.read_csv("/content/nba (1).csv", index_col="Name")
data.head(5)

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [ ]:
# dropping passed values
data.drop(["Avery Bradley", "John Holland", "R.J. Hunter"], inplace = True)
data

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
...,...,...,...,...,...,...,...,...
Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dropping Columns in Pandas with Column Name

In [ ]:
# dropping passed columns
data.drop(["Team", "Weight"], axis = 1, inplace = True)

# display
data.head()

               Number Position   Age Height    College      Salary
Name
Jae Crowder      99.0       SF  25.0    6-6  Marquette   6796117.0
Jonas Jerebko     8.0       PF  29.0   6-10        NaN   5000000.0
Amir Johnson     90.0       PF  29.0    6-9        NaN  12000000.0
Jordan Mickey    55.0       PF  21.0    6-8        LSU   1170960.0
Kelly Olynyk     41.0        C  25.0    7-0    Gonzaga   2165160.0

#Python | Pandas DataFrame.truncate

Pandas DataFrame.truncate() function is used to truncate a Series or DataFrame before and after some index value. This is a useful shorthand for boolean indexing based on index values above or below certain thresholds.

**Syntax: DataFrame.truncate(before=None, after=None, axis=None, copy=True)**

**Parameter :**
before : Truncate all rows before this index value.
after : Truncate all rows after this index value.
axis : Axis to truncate. Truncates the index (rows) by default.
copy : Return a copy of the truncated section.

**Returns : The truncated Series or DataFrame.**

In [ ]:
# importing pandas as pd
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({'Weight':[45, 88, 56, 15, 71],
                   'Name':['Sam', 'Andrea', 'Alex', 'Robin', 'Kia'],
                   'Age':[14, 25, 55, 8, 21]})

df

   Weight    Name  Age
0      45     Sam   14
1      88  Andrea   25
2      56    Alex   55
3      15   Robin    8
4      71     Kia   21

In [ ]:
# Create the index
ser= pd.date_range('2010-10-09 08:45', periods = 5, freq ='H')

In [ ]:
# Set the index
df.index = ser

In [ ]:
df

                     Weight    Name  Age
2010-10-09 08:45:00      45     Sam   14
2010-10-09 09:45:00      88  Andrea   25
2010-10-09 10:45:00      56    Alex   55
2010-10-09 11:45:00      15   Robin    8
2010-10-09 12:45:00      71     Kia   21

In [ ]:
# return the truncated dataframe
result = df.truncate(before = '2010-10-09 09:45:00', after = '2010-10-09 11:45:00')

# Print the result
result

                     Weight    Name  Age
2010-10-09 09:45:00      88  Andrea   25
2010-10-09 10:45:00      56    Alex   55
2010-10-09 11:45:00      15   Robin    8

In [ ]:
# importing pandas as pd
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({"A":[12, 4, 5, None, 1],
                   "B":[7, 2, 54, 3, None],
                   "C":[20, 16, 11, 3, 8],
                   "D":[14, 3, None, 2, 6]})

In [ ]:
df

      A     B   C     D
0  12.0   7.0  20  14.0
1   4.0   2.0  16   3.0
2   5.0  54.0  11   NaN
3   NaN   3.0   3   2.0
4   1.0   NaN   8   6.0

In [ ]:
# Create the index
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']

# Set the index
df.index = index_

# Print the DataFrame
df

          A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0

In [ ]:
# return the truncated dataframe
result = df.truncate(before = 'Row_3', after = 'Row_4')
result

         A     B   C    D
Row_3  5.0  54.0  11  NaN
Row_4  NaN   3.0   3  2.0

#Python | Pandas Series.truncate()

In [ ]:
# importing pandas as pd
import pandas as pd

# Creating the Series
sr = pd.Series([19.5, 16.8, 22.78, 20.124, 18.1002])
sr

0    19.5000
1    16.8000
2    22.7800
3    20.1240
4    18.1002
dtype: float64

In [ ]:
# truncate data outside the given range
sr.truncate(before = 1, after = 3)

1    16.800
2    22.780
3    20.124
dtype: float64

In [ ]:
# Creating the Series
sr = pd.Series([19.5, 16.8, 22.78, 20.124, 18.1002],index=['a','b','c','d','e'])
sr

a    19.5000
b    16.8000
c    22.7800
d    20.1240
e    18.1002
dtype: float64

In [ ]:
# truncate data outside the given range
sr.truncate(before = 'b', after = 'd')

b    16.800
c    22.780
d    20.124
dtype: float64

#Iterating over rows

 Below are the ways by which we can iterate over rows:

Iteration over rows using iterrows()

Iteration over rows using itertuples()

**Row Iteration Using iterrows()**

this function returns each index value along with a series containing the data in each row.

In [ ]:
# importing pandas as pd
import pandas as pd

# dictionary of lists
dict = {'name': ["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score': [90, 40, 80, 98]}

# creating a dataframe from a dictionary
df = pd.DataFrame(dict)

df

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [ ]:
# iterating over rows using iterrows() function
for i, j in df.iterrows():
    print(i, j)
    print()

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object

1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object

2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object

In [ ]:
# importing pandas module
import pandas as pd

# making data frame from csv file
data = pd.read_csv("/content/nba (1).csv")

data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i, j in data.iterrows():
    print(i, j)
    print()

Streaming output truncated to the last 5000 lines.
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: 3, dtype: object

4 Name         Jonas Jerebko
Team        Boston Celtics
Number                 8.0
Position                PF
Age                   29.0
Height                6-10
Weight               231.0
College                NaN
Salary           5000000.0
Name: 4, dtype: object

5 Name          Amir Johnson
Team        Boston Celtics
Number                90.0
Position                PF
Age                   29.0
Height                 6-9
Weight               240.0
College                NaN
Salary          12000000.0
Name: 5, dtype: object

6 Name         Jordan Mickey
Team        Boston Celtics
Number                55.0
Position                PF
Age                   21.0
Height                 6-8
Weight               235.0
College                LSU
Salary           1170960.0
Name: 6, dtype: object

7 Name          Kelly Olynyk
Team        Boston Celtics
Number                41.0
Position                 C
Age                   25.0
Height                 7-0
Weight               238.0
College            Gonzaga
Salary           2165160.0
Name: 7, dtype: object

8 Name          Terry Rozier
Team        Boston Celtics
Number                12.0
Position                PG
Age                   22.0
Height                 6-2
Weight               190.0
College         Louisville
Salary           1824360.0
Name: 8, dtype: object

9 Name          Marcus Smart
Team        Boston Celtics
Number                36.0
Position                PG
Age                   22.0
Height                 6-4
Weight               220.0
College     Oklahoma State
Salary           3431040.0
Name: 9, dtype: object

10 Name        Jared Sullinger
Team         Boston Celtics
Number                  7.0
Position                  C
Age                    24.0
Height                  6-9
Weight                260.0
College          Ohio State
Salary            2569260.0
Name: 10, dtype: object

11 Name         Isaiah Thomas
Team        Boston Celtics
Number                 4.0
Position                PG
Age                   27.0
Height                 5-9
Weight               185.0
College         Washington
Salary           6912869.0
Name: 11, dtype: object

12 Name           Evan Turner
Team        Boston Celtics
Number                11.0
Position                SG
Age                   27.0
Height                 6-7
Weight               220.0
College         Ohio State
Salary           3425510.0
Name: 12, dtype: object

13 Name           James Young
Team        Boston Celtics
Number                13.0
Position                SG
Age                   20.0
Height                 6-6
Weight               215.0
College           Kentucky
Salary           1749840.0
Name: 13, dtype: object

14 Name          Tyler Zeller
Team        Boston Celtics
Number                44.0
Position                 C
Age                   26.0
Height                 7-0
Weight               253.0
College     North Carolina
Salary           2616975.0
Name: 14, dtype: object

15 Name        Bojan Bogdanovic
Team           Brooklyn Nets
Number                  44.0
Position                  SG
Age                     27.0
Height                   6-8
Weight                 216.0
College                  NaN
Salary             3425510.0
Name: 15, dtype: object

16 Name          Markel Brown
Team         Brooklyn Nets
Number                22.0
Position                SG
Age                   24.0
Height                 6-3
Weight               190.0
College     Oklahoma State
Salary            845059.0
Name: 16, dtype: object

17 Name        Wayne Ellington
Team          Brooklyn Nets
Number                 21.0
Position                 SG
Age                    28.0
Height                  6-4
Weight                200.0
College      North Carolina
Salary            1500000.0
Name: 17, dtype: object

18 Name        Rondae Hollis-Jefferson
Team                  Brooklyn Nets
Number                         24.0
Position                         SG
Age                            21.0
Height                          6-7
Weight                        220.0
College                     Arizona
Salary                    1335480.0
Name: 18, dtype: object

19 Name         Jarrett Jack
Team        Brooklyn Nets
Number                2.0
Position               PG
Age                  32.0
Height                6-3
Weight              200.0
College      Georgia Tech
Salary          6300000.0
Name: 19, dtype: object

20 Name        Sergey Karasev
Team         Brooklyn Nets
Number                10.0
Position                SG
Age                   22.0
Height                 6-7
Weight               208.0
College                NaN
Salary           1599840.0
Name: 20, dtype: object

21 Name        Sean Kilpatrick
Team          Brooklyn Nets
Number                  6.0
Position                 SG
Age                    26.0
Height                  6-4
Weight                219.0
College          Cincinnati
Salary             134215.0
Name: 21, dtype: object

22 Name         Shane Larkin
Team        Brooklyn Nets
Number                0.0
Position               PG
Age                  23.0
Height               5-11
Weight              175.0
College        Miami (FL)
Salary          1500000.0
Name: 22, dtype: object

23 Name          Brook Lopez
Team        Brooklyn Nets
Number               11.0
Position                C
Age                  28.0
Height                7-0
Weight              275.0
College          Stanford
Salary         19689000.0
Name: 23, dtype: object

24 Name        Chris McCullough
Team           Brooklyn Nets
Number                   1.0
Position                  PF
Age                     21.0
Height                  6-11
Weight                 200.0
College             Syracuse
Salary             1140240.0
Name: 24, dtype: object

25 Name          Willie Reed
Team        Brooklyn Nets
Number               33.0
Position               PF
Age                  26.0
Height               6-10
Weight              220.0
College       Saint Louis
Salary           947276.0
Name: 25, dtype: object

26 Name        Thomas Robinson
Team          Brooklyn Nets
Number                 41.0
Position                 PF
Age                    25.0
Height                 6-10
Weight                237.0
College              Kansas
Salary             981348.0
Name: 26, dtype: object

27 Name           Henry Sims
Team        Brooklyn Nets
Number               14.0
Position                C
Age                  26.0
Height               6-10
Weight              248.0
College        Georgetown
Salary           947276.0
Name: 27, dtype: object

28 Name         Donald Sloan
Team        Brooklyn Nets
Number               15.0
Position               PG
Age                  28.0
Height                6-3
Weight              205.0
College         Texas A&M
Salary           947276.0
Name: 28, dtype: object

29 Name        Thaddeus Young
Team         Brooklyn Nets
Number                30.0
Position                PF
Age                   27.0
Height                 6-8
Weight               221.0
College       Georgia Tech
Salary          11235955.0
Name: 29, dtype: object

30 Name          Arron Afflalo
Team        New York Knicks
Number                  4.0
Position                 SG
Age                    30.0
Height                  6-5
Weight                210.0
College                UCLA
Salary            8000000.0
Name: 30, dtype: object

31 Name           Lou Amundson
Team        New York Knicks
Number                 17.0
Position                 PF
Age                    33.0
Height                  6-9
Weight                220.0
College                UNLV
Salary            1635476.0
Name: 31, dtype: object

32 Name        Thanasis Antetokounmpo
Team               New York Knicks
Number                        43.0
Position                        SF
Age                           23.0
Height                         6-7
Weight                       205.0
College                        NaN
Salary                     30888.0
Name: 32, dtype: object

33 Name        Carmelo Anthony
Team        New York Knicks
Number                  7.0
Position                 SF
Age                    32.0
Height                  6-8
Weight                240.0
College            Syracuse
Salary           22875000.0
Name: 33, dtype: object

34 Name          Jose Calderon
Team        New York Knicks
Number                  3.0
Position                 PG
Age                    34.0
Height                  6-3
Weight                200.0
College                 NaN
Salary            7402812.0
Name: 34, dtype: object

35 Name        Cleanthony Early
Team         New York Knicks
Number                  11.0
Position                  SF
Age                     25.0
Height                   6-8
Weight                 210.0
College        Wichita State
Salary              845059.0
Name: 35, dtype: object

36 Name        Langston Galloway
Team          New York Knicks
Number                    2.0
Position                   SG
Age                      24.0
Height                    6-2
Weight                  200.0
College        Saint Joseph's
Salary               845059.0
Name: 36, dtype: object

37 Name           Jerian Grant
Team        New York Knicks
Number                 13.0
Position                 PG
Age                    23.0
Height                  6-4
Weight                195.0
College          Notre Dame
Salary            1572360.0
Name: 37, dtype: object

38 Name            Robin Lopez
Team        New York Knicks
Number                  8.0
Position                  C
Age                    28.0
Height                  7-0
Weight                255.0
College            Stanford
Salary           12650000.0
Name: 38, dtype: object

39 Name           Kyle O'Quinn
Team        New York Knicks
Number                  9.0
Position                 PF
Age                    26.0
Height                 6-10
Weight                250.0
College       Norfolk State
Salary            3750000.0
Name: 39, dtype: object

40 Name        Kristaps Porzingis
Team           New York Knicks
Number                     6.0
Position                    PF
Age                       20.0
Height                     7-3
Weight                   240.0
College                    NaN
Salary               4131720.0
Name: 40, dtype: object

41 Name         Kevin Seraphin
Team        New York Knicks
Number                  1.0
Position                  C
Age                    26.0
Height                 6-10
Weight                278.0
College                 NaN
Salary            2814000.0
Name: 41, dtype: object

42 Name           Lance Thomas
Team        New York Knicks
Number                 42.0
Position                 SF
Age                    28.0
Height                  6-8
Weight                235.0
College                Duke
Salary            1636842.0
Name: 42, dtype: object

43 Name          Sasha Vujacic
Team        New York Knicks
Number                 18.0
Position                 SG
Age                    32.0
Height                  6-7
Weight                195.0
College                 NaN
Salary             947276.0
Name: 43, dtype: object

44 Name        Derrick Williams
Team         New York Knicks
Number                  23.0
Position                  PF
Age                     25.0
Height                   6-8
Weight                 240.0
College              Arizona
Salary             4000000.0
Name: 44, dtype: object

45 Name            Tony Wroten
Team        New York Knicks
Number                  5.0
Position                 SG
Age                    23.0
Height                  6-6
Weight                205.0
College          Washington
Salary             167406.0
Name: 45, dtype: object

46 Name               Elton Brand
Team        Philadelphia 76ers
Number                    42.0
Position                    PF
Age                       37.0
Height                     6-9
Weight                   254.0
College                   Duke
Salary                     NaN
Name: 46, dtype: object

47 Name             Isaiah Canaan
Team        Philadelphia 76ers
Number                     0.0
Position                    PG
Age                       25.0
Height                     6-0
Weight                   201.0
College           Murray State
Salary                947276.0
Name: 47, dtype: object

48 Name          Robert Covington
Team        Philadelphia 76ers
Number                    33.0
Position                    SF
Age                       25.0
Height                     6-9
Weight                   215.0
College        Tennessee State
Salary               1000000.0
Name: 48, dtype: object

49 Name               Joel Embiid
Team        Philadelphia 76ers
Number                    21.0
Position                     C
Age                       22.0
Height                     7-0
Weight                   250.0
College                 Kansas
Salary               4626960.0
Name: 49, dtype: object

50 Name              Jerami Grant
Team        Philadelphia 76ers
Number                    39.0
Position                    SF
Age                       22.0
Height                     6-8
Weight                   210.0
College               Syracuse
Salary                845059.0
Name: 50, dtype: object

51 Name            Richaun Holmes
Team        Philadelphia 76ers
Number                    22.0
Position                    PF
Age                       22.0
Height                    6-10
Weight                   245.0
College          Bowling Green
Salary               1074169.0
Name: 51, dtype: object

52 Name               Carl Landry
Team        Philadelphia 76ers
Number                     7.0
Position                    PF
Age                       32.0
Height                     6-9
Weight                   248.0
College                 Purdue
Salary               6500000.0
Name: 52, dtype: object

53 Name          Kendall Marshall
Team        Philadelphia 76ers
Number                     5.0
Position                    PG
Age                       24.0
Height                     6-4
Weight                   200.0
College         North Carolina
Salary               2144772.0
Name: 53, dtype: object

54 Name            T.J. McConnell
Team        Philadelphia 76ers
Number                    12.0
Position                    PG
Age                       24.0
Height                     6-2
Weight                   200.0
College                Arizona
Salary                525093.0
Name: 54, dtype: object

55 Name              Nerlens Noel
Team        Philadelphia 76ers
Number                     4.0
Position                    PF
Age                       22.0
Height                    6-11
Weight                   228.0
College               Kentucky
Salary               3457800.0
Name: 55, dtype: object

56 Name             Jahlil Okafor
Team        Philadelphia 76ers
Number                     8.0
Position                     C
Age                       20.0
Height                    6-11
Weight                   275.0
College                   Duke
Salary               4582680.0
Name: 56, dtype: object

57 Name                 Ish Smith
Team        Philadelphia 76ers
Number                     1.0
Position                    PG
Age                       27.0
Height                     6-0
Weight                   175.0
College            Wake Forest
Salary                947276.0
Name: 57, dtype: object

58 Name              Nik Stauskas
Team        Philadelphia 76ers
Number                    11.0
Position                    SG
Age                       22.0
Height                     6-6
Weight                   205.0
College               Michigan
Salary               2869440.0
Name: 58, dtype: object

59 Name           Hollis Thompson
Team        Philadelphia 76ers
Number                    31.0
Position                    SG
Age                       25.0
Height                     6-8
Weight                   206.0
College             Georgetown
Salary                947276.0
Name: 59, dtype: object

60 Name            Christian Wood
Team        Philadelphia 76ers
Number                    35.0
Position                    PF
Age                       20.0
Height                    6-11
Weight                   220.0
College                   UNLV
Salary                525093.0
Name: 60, dtype: object

61 Name        Bismack Biyombo
Team        Toronto Raptors
Number                  8.0
Position                  C
Age                    23.0
Height                  6-9
Weight                245.0
College                 NaN
Salary            2814000.0
Name: 61, dtype: object

62 Name          Bruno Caboclo
Team        Toronto Raptors
Number                 20.0
Position                 SF
Age                    20.0
Height                  6-9
Weight                205.0
College                 NaN
Salary            1524000.0
Name: 62, dtype: object

63 Name        DeMarre Carroll
Team        Toronto Raptors
Number                  5.0
Position                 SF
Age                    29.0
Height                  6-8
Weight                212.0
College            Missouri
Salary           13600000.0
Name: 63, dtype: object

64 Name          DeMar DeRozan
Team        Toronto Raptors
Number                 10.0
Position                 SG
Age                    26.0
Height                  6-7
Weight                220.0
College                 USC
Salary           10050000.0
Name: 64, dtype: object

65 Name          James Johnson
Team        Toronto Raptors
Number                  3.0
Position                 PF
Age                    29.0
Height                  6-9
Weight                250.0
College         Wake Forest
Salary            2500000.0
Name: 65, dtype: object

66 Name            Cory Joseph
Team        Toronto Raptors
Number                  6.0
Position                 PG
Age                    24.0
Height                  6-3
Weight                190.0
College               Texas
Salary            7000000.0
Name: 66, dtype: object

67 Name             Kyle Lowry
Team        Toronto Raptors
Number                  7.0
Position                 PG
Age                    30.0
Height                  6-0
Weight                205.0
College           Villanova
Salary           12000000.0
Name: 67, dtype: object

68 Name         Lucas Nogueira
Team        Toronto Raptors
Number                 92.0
Position                  C
Age                    23.0
Height                  7-0
Weight                220.0
College                 NaN
Salary            1842000.0
Name: 68, dtype: object

69 Name        Patrick Patterson
Team          Toronto Raptors
Number                   54.0
Position                   PF
Age                      27.0
Height                    6-9
Weight                  235.0
College              Kentucky
Salary              6268675.0
Name: 69, dtype: object

70 Name          Norman Powell
Team        Toronto Raptors
Number                 24.0
Position                 SG
Age                    23.0
Height                  6-4
Weight                215.0
College                UCLA
Salary             650000.0
Name: 70, dtype: object

71 Name          Terrence Ross
Team        Toronto Raptors
Number                 31.0
Position                 SF
Age                    25.0
Height                  6-7
Weight                195.0
College          Washington
Salary            3553917.0
Name: 71, dtype: object

72 Name             Luis Scola
Team        Toronto Raptors
Number                  4.0
Position                 PF
Age                    36.0
Height                  6-9
Weight                240.0
College                 NaN
Salary            2900000.0
Name: 72, dtype: object

73 Name         Jason Thompson
Team        Toronto Raptors
Number                  1.0

**Row Iteration Using itertuples()**
this function return a tuple for each row in the DataFrame. The first element of the tuple will be the row’s corresponding index value, while the remaining values are the row values.

this function iterates over each column as key, value pair with the label as key, and column value as a Series object.

In [ ]:
# importing pandas as pd
import pandas as pd

# dictionary of lists
dict = {'name': ["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score': [90, 40, 80, 98]}
df=pd.DataFrame(dict)
df

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [ ]:
# using a itertuples()
for i in df.itertuples():
    print(i)

Pandas(Index=0, name='aparna', degree='MBA', score=90)
Pandas(Index=1, name='pankaj', degree='BCA', score=40)
Pandas(Index=2, name='sudhir', degree='M.Tech', score=80)
Pandas(Index=3, name='Geeku', degree='MBA', score=98)

#Pandas Iterate Over Columns of DataFrame

In [ ]:
# importing pandas as pd
import pandas as pd

# dictionary of lists
dict = {'name': ["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score': [90, 40, 80, 98]}

# creating a dataframe from a dictionary
df = pd.DataFrame(dict)

df

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [ ]:
list(df)

['name', 'degree', 'score']

In [ ]:
# creating a list of dataframe columns
columns = list(df)

for i in columns:

    # printing the third element of the column
    print(df[i][2])

sudhir
M.Tech
80

#Python | Pandas Dataframe.sort_values()

 Pandas sort_values() function sorts a data frame in Ascending or Descending order of passed Column. It’s different than the sorted Python function since it cannot sort a data frame and a particular column cannot be selected.

**Syntax:** DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind=’quicksort’, na_position=’last’)

> Add blockquote

**Parameters: **

by: Single/List of column names to sort Data Frame by.

axis: 0 or ‘index’ for rows and 1 or ‘columns’ for Column.

ascending: Boolean value which sorts Data frame in ascending order if True.

inplace: Boolean value. Makes the changes in passed data frame itself if True.

kind: String which can have three inputs(‘quicksort’, ‘mergesort’ or ‘heapsort’) of algorithm used to sort data frame.

na_position: Takes two string input ‘last’ or ‘first’ to set position of Null values. Default is ‘last’.

**Return Type:**

Returns a sorted Data Frame with Same dimensions as of the function caller DataFrame.

In [ ]:
# importing pandas package
import pandas as pd

# making data frame from csv file
data = pd.read_csv("/content/nba (1).csv")

# display
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# sorting data frame by name
data.sort_values("Name", axis=0, ascending=True,
                 inplace=True, na_position='last')

# display
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...,...,...
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# sorting data frame by name
data.sort_values("Salary", axis=0, ascending=True,
                 inplace=True, na_position='first')

data
# display

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,NaN
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0

####Dataframe.sort_values() Multiple Parameter Sorting:

In [ ]:
#sorting data frame by Team and then By names
data.sort_values(["Team", "Name"], axis=0,
                 ascending=True, inplace=True)

#display
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
318,Dennis Schroder,Atlanta Hawks,17.0,PG,22.0,6-1,172.0,NaN,1763400.0
323,Jeff Teague,Atlanta Hawks,0.0,PG,27.0,6-2,186.0,Wake Forest,8000000.0
309,Kent Bazemore,Atlanta Hawks,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940.0
...,...,...,...,...,...,...,...,...,...
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000.0
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,NaN,13000000.0
378,Otto Porter Jr.,Washington Wizards,22.0,SF,23.0,6-8,198.0,Georgetown,4662960.0
379,Ramon Sessions,Washington Wizards,7.0,PG,30.0,6-3,190.0,Nevada,2170465.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The Team is sorted first in Ascending order and then the Names are sorted in ascending order for every Team name.

We can also pass a list to the ‘ascending’ Parameter to tell pandas which column to sort how.
The index of Boolean in ‘ascending’ parameter should be same as the index of column name in ‘by’ Parameter.

In [ ]:
#sorting data frame by Team and then By names
data.sort_values(["Team", "Name"], axis=0,
                 ascending=[True,False], inplace=True)

#display
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520.0
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,NaN,9756250.0
320,Thabo Sefolosha,Atlanta Hawks,25.0,SF,32.0,6-7,220.0,NaN,4000000.0
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659.0
...,...,...,...,...,...,...,...,...,...
380,Garrett Temple,Washington Wizards,17.0,SG,30.0,6-6,195.0,LSU,1100602.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

 the data frame is sorted in ascending of Team name and for every Team name, the Names are sorted in descending order.

In [ ]:
#sorting data frame by Team, age and height
data.sort_values(["Team", "Age", "Height"], axis=0,
                 ascending=[False,True,False],
inplace=True)

#display
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
377,Kelly Oubre Jr.,Washington Wizards,12.0,SF,20.0,6-7,205.0,Kansas,1920240.0
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674.0
378,Otto Porter Jr.,Washington Wizards,22.0,SF,23.0,6-8,198.0,Georgetown,4662960.0
371,Jarell Eddie,Washington Wizards,8.0,SG,24.0,6-7,218.0,Virginia Tech,561716.0
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950.0
...,...,...,...,...,...,...,...,...,...
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,NaN,9756250.0
320,Thabo Sefolosha,Atlanta Hawks,25.0,SF,32.0,6-7,220.0,NaN,4000000.0
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479.0
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The team name is sorted first, then the Age and for every age, the height is sorted. In the Team “Washington Wizards” there are 3 Players with age 30. Those 3 people are sorted by their Height in ascending order.

#How to add one row in an existing Pandas DataFrame?

**Add Row to Dataframe using df.loc**

In [ ]:
dict = {'Name':['Martha', 'Tim', 'Rob', 'Georgia'],
        'Maths':[87, 91, 97, 95],
        'Science':[83, 99, 84, 76]
       }

df = pd.DataFrame(dict)

display(df)

      Name  Maths  Science
0   Martha     87       83
1      Tim     91       99
2      Rob     97       84
3  Georgia     95       76

In [ ]:
len(df.index)

4

In [ ]:
df.loc[:,'address']=address

In [ ]:
df.loc[len(df.index)] = ['Amy', 89, 93]

display(df)

      Name  Maths  Science
0   Martha     87       83
1      Tim     91       99
2      Rob     97       84
3  Georgia     95       76
4      Amy     89       93

**Pandas Add Row to Dataframe using df.append**

In [ ]:
dict = {'Name':['Martha', 'Tim', 'Rob', 'Georgia'],
        'Maths':[87, 91, 97, 95],
        'Science':[83, 99, 84, 76]
       }

df = pd.DataFrame(dict)

display(df)

In [ ]:
df2 = {'Name': 'Amy', 'Maths': 89, 'Science': 93}
df = df._append(df2, ignore_index = True)

display(df)

      Name  Maths  Science
0   Martha     87       83
1      Tim     91       99
2      Rob     97       84
3  Georgia     95       76
4      Amy     89       93
5      Amy     89       93
6      Amy     89       93

#Pandas Add Row to Dataframe using Concat

In [ ]:
dict = {'Name':['Martha', 'Tim', 'Rob', 'Georgia'],
        'Maths':[87, 91, 97, 95],
        'Science':[83, 99, 84, 76]
       }

df1 = pd.DataFrame(dict)
df1

      Name  Maths  Science
0   Martha     87       83
1      Tim     91       99
2      Rob     97       84
3  Georgia     95       76

In [ ]:
import pandas as pd
import numpy as np

dict = {'Name':['Martha', 'Tim', 'Rob', 'Georgia'],
        'Maths':[87, 91, 97, 95],
        'Science':[83, 99, 84, 76]
       }

df1 = pd.DataFrame(dict)
display(df1)

      Name  Maths  Science
0   Martha     87       83
1      Tim     91       99
2      Rob     97       84
3  Georgia     95       76

In [ ]:
dict = {'Name':['Amy', 'Maddy'],
        'Maths':[89, 90],
        'Sci
        ence':[93, 81]
       }

df2 = pd.DataFrame(dict)
display(df2)

df3 = pd.concat([df1, df2], ignore_index = True)
df3.reset_index()

display(df3)

    Name  Maths  Science
0    Amy     89       93
1  Maddy     90       81

      Name  Maths  Science
0   Martha     87       83
1      Tim     91       99
2      Rob     97       84
3  Georgia     95       76
4      Amy     89       93
5    Maddy     90       81

In [ ]:
print(df.groupby('Name').groups)

{'Georgia': [3], 'Martha': [0], 'Rob': [2], 'Tim': [1]}